### ISSUE TITLE
I think this repository needs a tag

### ISSUE THREAD

**Issue by xrl** [mozilla/sccache-action#18]
The comment from the README doesn't work, I had to pin the action to a sh256:

```
      - name: Run sccache-cache
        uses: mozilla/sccache-action@eaed7fb9f8fb32adea8bd40d7f276f312de9beaf
        with:
          version: "v0.3.3"

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
```
